framework/lib/components/overflow-group/overflow-group.tsx
When scaling up the isLocked.current ref was set to true when it should reset if the container dimensions change This is fixed by adding another useEffect.
Before:
https://user-images.githubusercontent.com/90923099/220159695-20887124-cdbf-430f-9331-78e69456bf63.mov
After:
https://user-images.githubusercontent.com/90923099/220159721-3d261e07-fe04-418b-b78d-bd87c6e21ae2.mov
=> fix(framework): overflow group responsive issue

framework/lib/components/form/types.ts, framework/sandbox/docs/pages/field-page/index.tsx
In some cases one wants to render an input element without the need of a visible label, that might
not be apart of the sketches. The types should reflect this
=> fix(framework): make label prop optional on field

framework/lib/components/form/form.tsx, framework/lib/components/form/types.ts, framework/sandbox/docs/pages/form-page/index.tsx
Previousely the form context was closed within
the <Form> tag itself, thus the form context api
was not available to methods outside of it, and
the form had to be refactored with the useForm hook to work properly.
Now a ref has been added that should act as syntax sugar to simplify this process
=> fix(framework): access to form context api via ref

framework/lib/components/toolbox/toolbox.tsx
When a value from the theme cannot be resolved we should
import the appriopiate value from @northlight/tokens
and resolve it ourselves.
=> fix(framework): update toolbox z-index with token value

framework/sandbox/docs/pages/card-page/index.tsx
Temporary fix for the card component that shows white background on a Dark theme when deployed via Netlify.
=> Netlify card component darkmode fix

framework/lib/components/clickable/clickable.tsx
Idk why, the linkProps prop works fine in the sandbox enviroment in northlight.
But when trying in the domain sandbox the text decoration is still underline
Defaulting it to have no textDecoration should fix it, and we should probably
have it like that anyway, as when you use the clickable as a wrapper you 
don't want the text to be underlined
=> fix(framework): change default textDecoration

framework/sandbox/icons/app.tsx
Added transparent background to the card. It seems that inherits white bg in dark mode while in production. Locally seems fine.
=> fix(framework): Card showing white bg on production in dark mode

framework/README.md, framework/package.json, framework/sandbox/docs/app.tsx, framework/sandbox/docs/pages/file-picker-page/index.tsx
small change of the name mediatool to northlight. Seems like we forgot to update it in some places.
=> chore(framework): change names from mediatool to northlight

framework/lib/theme/index.ts, framework/lib/theme/skins/tott/index.ts, framework/lib/theme/skins/webapp/index.ts, tokens/lib/tokens.json
Contains the addition of about 84 new tokens:
bg.base
bg.layer
bg.overlayer
bg.brand.active
bg.brand.hover
bg.brand.default
bg.secondary.active
bg.secondary.hover
bg.secondary.default
bg.tertiary.active
bg.tertiary.hover 
bg.tertiary.default
bg.success.active
bg.success.hover
 bg.success.default
bg.error.active
bg.error.hover
bg.error.default
bg.warning.active
bg.warning.hover
 bg.warning.default
bg.info.active
bg.info.hover
 bg.info.default
bg.ghost.active
bg.ghost.hover
bg.ghost.default
bg.filled
border.hover
border.default
border.error
border.warning
border.info
border.success
border.brand.active
border.brand.hover
border.brand.default
border.secondary.active
border.secondary.hover
border.secondary.default
border.tertiary.active
border.tertiary.hover
border.tertiary.default
  …
=> feat(tokens): 84 New tokens

framework/package.json
react-router-dom is currently used by components such as Navbaritem so it should be listed as normal package dependency for now
=> chore(framework): move dep react-router-dom

framework/lib/components/select/types.ts
added missing type for customOption so that it can be used in typescript files.
=> fix(framework): add type for custom option

framework/lib/theme/index.ts
This fixes an issue with the theme where the scrollbars placeholders were always visible on the page regardless of scrolling or not.
=> fix: remove overflow:scroll on html element

framework/lib/components/avatar/types.ts
This is because we spread the rest on an HStack.
=> fix(framework): extends stack props for avatar group

framework/lib/components/date-picker/components/calendar/range-calendar.tsx, framework/lib/components/date-picker/components/calendar/simple-range-calendar.tsx, framework/lib/components/date-picker/components/calendar/types.ts, framework/lib/components/date-picker/date-picker-field/date-range-picker-field.tsx, framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/package.json
added isClearable prop for range calendar. Reason for this is that we have clear button inside calendar picker. Even though we have isClearable false or true , it was always visible.
=> chore(framework): added isClearable for range calendar

docs/src/docs/pages/date-range-picker-page/index.tsx
updated date range picker documentation to show an example of isClearable true/false. Reason for that is that we recently updated isClearable
=> chore(docs): updated date range picker docs

README.md, docs/package.json, nx.json
With this, you should start the docs server running `yarn nx dev`.
=> fix: configure nx to transpile before dev

framework/lib/components/drag-and-drop/sortable-list.tsx
Removed the useEffects that can add infinte rerenders if using onChange callback
=> fix(framework): fix infinite rerender in sorable list

framework/lib/components/switch/switch-field.tsx, framework/lib/components/switch/types.ts
- Fixes the issue with the strange spacing between <Switch> and the generated <Label> 
- The new prop `labelPosition` gives an opportunity to select whether you want the label to be on the "left" or "right" of the <Switch>
- Basic usage added to the reference page
closes: DEV-8557
=> chore(northlight): new labelPosition prop for SwitchField

docs/src/docs/pages/date-range-picker-page/index.tsx, framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts, framework/lib/components/date-picker/components/calendar/quick-navigation/quick-select.tsx, framework/lib/components/date-picker/components/calendar/quick-navigation/types.ts, framework/lib/components/date-picker/components/calendar/range-calendar.tsx, framework/lib/components/date-picker/components/calendar/simple-range-calendar.tsx, framework/lib/components/date-picker/components/calendar/types.ts, framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/lib/components/date-picker/types.ts
Adds a new prop fiscalStartDay as prop to all the calendars/date pickers, which solves the issue of having no exact starting day from the fiscal year settings  when creating a new plan 
closes: DEV-8742
=> feat(northlight): datePicker-calendar fiscalStartDay prop

framework/lib/components/form/field.tsx, framework/lib/components/form/types.ts
This commit implements generic types forwarding in the Field component. This is neccessary to provide an easy way to refer to a form state within a Field component callback.
Previously, with no generics support, the logic would reference "any" in "value" and "onChange":
```
<Field name="name">
{
({ value: any }) => (...)
}
</Field>
```
With the generics support the developer can pass down the form body interface to the Field component, to ensure that "value" and "onChange" have valid instance type:
```
<Field<MyFormBody> name="name">
{
({ value: 'Alex' | 'Mark' }) => (...)
}
</Field>
```
It's now also possible to pass the `control` prop to achieve the same effect:
```
<Form initialValues={ { username: 'Alice' } }>
{
({ control }) => (
<Field name="username" control={ control }>
{
({ value …
```
=> chore: add generics support for Field

framework/lib/components/button/types.ts, framework/lib/theme/components/button/index.ts
Buttons now have a brandSubdued variant, which is basically an inverted brand button, This applies to all buttons across the design system
closes: DEV-7888
=> chore(northlight): new button variant brandSubdued

framework/lib/components/select/select-field.tsx, framework/lib/components/select/types.ts
when asserting type of event passed in callback to onchange prop in selectfield it would not be compatible with the expected type. change to account for cases of ismulti is false and true respectively
=> fix(framework): change selectfieldtype

framework/lib/components/stack/index.ts
This commit exports the StackProps interface,
which is used a props for HStack, VStack and similar.
Export of props interfaces is one of the core principles of good Typescript code. It's essential Needed for good integration with 3rd parties.
=> chore(framework): export StackProps interface

framework/lib/components/flip-button/flip-button.tsx
when used with no icon text would be shifted to the right.
=> fix(framework): center text in flip button

framework/lib/components/form/field.tsx, framework/lib/components/form/types.ts
This commit exposes styling props for the Field
component, which allows manual and custom styling
when using the component in a real application.
This is implemented by applying non-used component props to the Stack component in use, allowing for flexible integration with other layout elements.
--
https://app.clickup.com/t/758254/DEV-9228
=> fix(framework): expose styling props for Field

framework/lib/components/search-bar/get-components.tsx, framework/lib/components/search-bar/search-bar.tsx, framework/lib/components/select/select.tsx
Reason for northlight docs search components bar getting stuck was becuase of newly added Control to select. Don't know why that caused a problem but it was not needed so made optional. Does not seem to cause any issues with normal select, only search bar
closed DEV-9227
=> fix(framework): fix broken search bar northlight docs

framework/lib/components/step-stack/step-stack.tsx, framework/lib/components/step-stack/types.ts
it is now possible to pass an alignItems prop to the step stack in order to center the circles vertically
=> feature(northlight): align items on stepstack

framework/lib/components/date-picker/date-picker/date-picker.tsx
@ilija- @magnusohlin This is a "dirty" fix. Can potentially be merged now to fix the symptom.
---
This commit fixes the issue when DatePicker controls would overlap the multi-select dropdown. Since, the datePicker controls should be on the same layer as the input, the zIndex value was reduced to 0.
=> fix(framework): reduce zIndex for datePicker controls

framework/lib/components/button/button.tsx, framework/lib/components/button/types.ts
This commit fixes the issue when specifying "as" property on the button component would not lead to the base component inferring props from component specified in "as".
This code would throw an error saying that "layoutId" is not a valid property:
<HStack as={motion.div} layoutId="a" />
This commit fixes the issue, by parsing available assume component props and appending them to the base props (ButtonProps).
=> fix(framework): support types for "as" component in Button

framework/package.json, framework/rollup.config.mjs
Sinced type is now module, es files now end with js and cjs files end
with cjs.
=> fix(framework): adjust file suffixes of transpiled files

framework/lib/components/editable-text/editable-text.tsx, framework/lib/theme/components/editable-text/index.ts
https://github.com/mediatool/northlight/assets/90923099/86715332-35e7-4a93-bbe1-cf185efdcac5
@unganemo it seems to me that the placeholder actually looked like the value instead of a placeholder. I changed the color which should clear up any confusion.
=> fix(framework): changed placeholder color editabletext

framework/lib/components/text-field/formatted-number-input.tsx, framework/lib/components/text-field/types.ts
https://github.com/mediatool/northlight/assets/90923099/6c008700-4822-4184-8e8c-565d2a592908
This PR:
- enables the user to remove last number from input field
- properly sets min and max value on blur
- allows formatted number input to take an inputrightelement
=> fix(framework): formatted number input bugs fixes

framework/lib/components/date-picker/date-picker/date-picker.tsx, framework/lib/components/date-picker/date-picker/date-range-picker.tsx
Fixed the daterange picker vertical-alignment
closes: DEV-9365
=> fix(northlight/components): fix datepicker trigger alignment

framework/lib/components/checkbox/checkbox-field.tsx, framework/lib/components/date-picker/date-picker-field/date-picker-field.tsx, framework/lib/components/date-picker/date-picker-field/date-range-picker-field.tsx, framework/lib/components/drag-and-drop/drag-item.tsx, framework/lib/components/flip-button/flip-button-group-field.tsx, framework/lib/components/form-control/form-label.tsx, framework/lib/components/form/field.tsx, framework/lib/components/number-input/number-input-field.tsx, framework/lib/components/radio/radio-group-field.tsx, framework/lib/components/search-bar/search-bar-field.tsx, framework/lib/components/select/select-field.tsx, framework/lib/components/switch/switch-field.tsx, framework/lib/components/tag/tag.tsx, framework/lib/components/text-field/formatted-number-input-field.tsx, framework/lib/components/text-field/text-field.tsx, framework/lib/components/textarea/textarea-field.tsx, framework/lib/components/typography/labels/label.tsx
The tooltip was weirdly placed on all field components, as well as formlabel and label. This was due to a ref not being passed down, and so the tooltip did not know where to render and rendered in upper corner.
closed: DEV-9728
=> fix(framework): tooltip not working on multiple components

framework/lib/components/select/constants.ts, framework/lib/components/select/select.tsx, framework/lib/components/select/types.ts, framework/lib/components/select/use-adaptive-menu-placement.ts
This will make it so the select dropdown will be displayed on top of the select input in case there is not enough space at the bottom. This applies for all container, including modal.
closed: DEV-9724
https://github.com/mediatool/northlight/assets/90923099/20539948-64c0-469e-ba2d-a56263b305f0
=> fix(framework): Select dropdown direction if cant fit in modal

framework/lib/components/steps/step.tsx, framework/lib/theme/components/steps/step/index.ts
If a step is disabled then it will not be marked as clickable
closed: DEV-9742
https://github.com/mediatool/northlight/assets/90923099/1f6c8b61-cc8c-4976-a0d3-a503225de7d9
=> fix(framework): make steps properly disabled

framework/lib/components/button/button.tsx, framework/lib/components/button/types.ts
https://github.com/mediatool/northlight/assets/90923099/fdbfabc8-83ab-4575-a893-4894ab96b4c8
The spinner that was used for the loading state of the button was actually the default spinner provided by Chakra UI. By chaning the default spinner for our own spinner this fixed the issue
closed: DEV-9732
=> fix(framework): change chakra ui spinner to northlight spinner

framework/lib/components/search-bar/get-components.tsx, framework/lib/components/select/types.ts, framework/lib/general.d.ts
This will generalize the existing leftIcon prop into being able to pass any React node to the left of the select input box
closed: DEV-9895
=> fix(framework): turn leftIcon into leftComponent

framework/lib/components/date-picker/components/calendar/date-select/month-select.tsx, framework/lib/components/date-picker/components/calendar/quick-navigation/adjust-range.tsx, framework/lib/components/date-picker/components/calendar/quick-navigation/button-row.tsx
This PR should directly help improve the Date Range picker UI/UX slightly by increasing some spacing, fixing the month select button that did not work, hiding the adjust range menu when it was supposed to be hidden, and renaming move date to move date by in the adjust menu
=> fix(framework): improve date range picker UI/UX

framework/lib/components/toolbox/toolbox.tsx, framework/lib/components/toolbox/types.ts
-Added some styling for resizing hold & drag
-Added one more prop for `resizeLimit` which can be 'half' and 'full' ( default is full ) so you can limit the resizing of the toolbox which can come in handy in future
https://github.com/mediatool/northlight/assets/5406237/ab1a5a32-8ce3-4fea-8fc8-7478373ad9a7
=> chore(northlight): toolbox component enhancement

framework/lib/components/number-input/number-input-stepper.tsx, framework/lib/components/number-input/number-input.tsx, framework/lib/components/number-input/types.ts
closed DEV-10277
For the Number Input with OnlyAcceptPercentage set to true: 
Before:
After:
=> fix(framework): fix percentage sign not showing

framework/lib/components/pin-input/types.ts, framework/lib/components/status-pin/pin-variant-map.ts, framework/lib/components/status-pin/status-pin.tsx
change colors to have more contrast to background, add new variants and add all variants to example presentation in northlight
Closes: DEV-10293
=> chore(framework): fix colors and example presentation for status pin

framework/lib/components/modal/index.ts, framework/lib/components/modal/modal-base.tsx, framework/lib/components/modal/modal.tsx, framework/lib/components/toolbox/toolbox-header.tsx, framework/lib/theme/components/modal/index.ts
change header to H4 in modal and toolbox
Closes: DEV-10299
=> chore(framework): change header to H4 in modal and toolbox

tokens/lib/tokens.json
Edited tokens for bottom and top paddings in the modal header from 1 rem to 1.25 rem to keep the close button centered after changing the heading style from h3 to h4
=> fix(northlight): edited padding tokens in the modal header

framework/lib/components/icon-button/icon-button.tsx
previousely you could not set a custom size for the icon in an iconbutton as it would be overriden, this should clear up confusion, so if a size for the icon is specified that will be used, and if not then the size of the icon button will be used instead
=> fix(framework): do not override icon size

icons/assets/stages-duo.svg, icons/assets/stages-solid.svg
fixes the issue with the stages icon aligning top in in viewBox.
From this:
To this:
=> fix(norhtlight/icons): stages icon viewBox fix

tokens/lib/tokens.json
Added an alternate set of tokens for text on a coloured background ('over-alt') in web app and tott skins. Created specific component tokens for text in button's variants. Added standard brand, success and danger tokens for text on a white background
=> chore (northlight): new color tokens for text

framework/lib/components/search-bar/get-components.tsx
Due to recent changes, the select menu is rendered in a portal this means it needs a separate testid from the select itself
=> fix(framework): add custom test-id to select menu component

framework/lib/theme/components/badge/index.ts, framework/lib/theme/components/button/index.ts, framework/lib/theme/components/tag/index.ts
This PR fixes two recent bugs:
1. Random blue color – the default button variant was recently changed to have color set to blue.500, since a lot of components, especially text and icons are wrapped in a <Button /> this made them blue
2. Badge and Tag weird colors. The text color of all badge and tag children were set to white unless colorScheme was set to yellow. Using getContrastColor together with useToken instead ensures that the correct text color is used
=> fix(framework): fix broken token colors

framework/lib/components/alert/types.ts, framework/lib/components/toast/toast.tsx, framework/lib/components/toast/types.ts, framework/lib/components/tooltip/tooltip.tsx, framework/lib/components/tooltip/types.ts, framework/lib/components/types/toastIconMap/index.ts, framework/lib/theme/components/alert/index.ts, framework/lib/theme/components/tooltip/index.ts
A couple of `toast`, `alert`, and `tooltip` component updates, including:
- Resolved TypeErrors in both light and dark modes caused by undefined properties.
- Addressed console errors related to unassigned or unidentified icons in the `toastIconMap`.
- Updated and correctly assigned design tokens.
- Revised styles for specific component variants.
- Implemented new `ai` and `ghost` variants, precisely matching the latest updates in the Figma component library (1:1 correspondence).
- Enhanced type definitions for the `tooltip`, and updated the types for both `tooltip` and `alert` components.
- `tooltip` now has `hasIcon={ true / false }` option
- Various minor layout fixes in the mentioned components.
closes: DEV-10296
**Sneak peek:**
=> chore(norhtlight): toast, alert, and tooltip updates

framework/lib/components/tooltip/tooltip.tsx, framework/lib/components/tooltip/types.ts
changed tooltip type to accept JSX and also added an example
=> fix(framework): add jsx to tooltip type

framework/lib/components/select/select.tsx
Clearing the value for select component with isClearable set to true and isMulti set to false didn't work. Therefor I passed the prop isClearable, default to false, to ChakraReactSelect.
Closes: DEV-11057
=> fix(framework): select is clearable

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx, framework/lib/components/createable-select-dropdown/types.ts, framework/lib/components/select/types.ts
the selection will now be reset if the user is clicking outside the select box, if the currently selected option is a creation option.
https://github.com/mediatool/northlight/assets/81630176/950a5696-b3e0-4130-bdac-3a26107f77fe
=> fix(framework-createable-select-dropdown): reset selection

framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/lib/components/date-picker/types.ts
Rendering the DateRangePicker in portal by default can cause problems with useOutsideClick, therefore this should be optional.
With Portal:
Without Portal:
=> fix(framework): date-range-picker portal be optional

framework/lib/components/select/select-field.tsx
Previousely if you had two options, where one of the option strings was a substring of the other option string, then when trying to select one of them the other one would also become selected
=> fix(framework): select-field incorrect value

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx, framework/lib/components/createable-select-dropdown/custom-components.tsx, framework/lib/components/editable-text/editable-controls.tsx, framework/lib/components/editable-text/editable-text.tsx, framework/lib/components/editable-text/types.ts, framework/lib/components/select/types.ts, framework/lib/general.d.ts
The CreatableSelectDropdown component has been updated to improve its functionality. When a user selects to "Add Field," the element now transitions from an Option to EditableText, streamlining the user experience. This enhancement allows for a more seamless process in adding fields, complete with appropriate 'Submit' and 'Cancel' buttons. Additionally, a new variant has been introduced, enabling color customization of the component.
closes: DEV-12420
=> fix(framework): createableselectdropdown has new add new field option

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx
I've enhanced the CreatableSelectDropdown component by introducing support for restProps. This allows it to accept additional properties, such as 'isDisabled'. Furthermore, I've implemented a useEffect hook that activates when the 'value' prop changes, addressing the previous rendering issues.
=> fix(framework): fix(framework): fix render and props in dropdown

framework/lib/components/date-picker/components/calendar/components/get-week-number-start-of-month.ts
Just had to add +1 to the totalDaysUntilMonth counter to take into account the first day of a month
closed DEV-12024
=> fix(framework): fix wrong week numbers in date range picker

framework/lib/theme/components/button/index.ts
Fixed the default button still having the black text, now updated with the brand one.
closes: DEV-12922
**Before:**
**After:**
**Dark mode** (still the same):
=> fix(northlight): default button style update

framework/lib/components/tabs/tabs.tsx, framework/lib/theme/components/tabs/index.ts
Updated the tabs docs.
Updated the style for the variants: `soft-rounded` and `line`, and added one more variant - `rounded`
Intro:
https://github.com/mediatool/northlight/assets/5406237/943f4927-aac9-4a2d-b4b9-d34d6e6f6288
Dark mode check:
closes: DEV-12918
=> fix(norhtlight): tabs docs and styling update

framework/lib/components/select/select.tsx
There is currently no indication that the select is clickable apart form the caret. This commit adds a cursor pointer to the box element containing the select to clearly show that it is clickable.
DEV-14454
=> fix(framework): add cursor pointer to select component

framework/lib/components/date-picker/date-picker/date-picker-locale-wrapper.tsx, framework/lib/components/date-picker/date-picker/date-picker.tsx, framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/lib/components/date-picker/date-picker/index.ts
This commit resolves the issue where the labels and dates did not correspond correctly in the grid. The underlying issue was that the imported library component does not currently support switching the first day of the week directly; this setting is controlled via the locale.
To address this issue, the component is now wrapped with a provider that sets the locale based on the user's selected setting. This ensures that the labels align correctly with their respective dates. 
closes: #DEV-14275
=> fix(northlight-ui): fix firstdayofweek in calendar

framework/lib/components/status-pin/pin-size-map.ts, framework/lib/components/status-pin/pin-variant-map.ts, framework/lib/components/status-pin/status-pin.tsx
Updated innerPin size for lg to be 4 instead of 3.5 to improve consistency of padding and scaling between size variants. Adjusted colorVariant mapping to use semantic tokens instead of green.500 etc and set bg to transparent. 
Updated documentation by adding more details, linking to related badge component and improving the usage presentation.
Closes: DEV-14603
=> chore(northlight): Add semantic colors and cons padding to StatusPin

framework/lib/components/badge/badge.tsx, framework/lib/components/badge/types.ts, framework/lib/theme/components/badge/index.ts
Description
This PR enhances the Badge component by introducing size variants and ensuring that the colorScheme property is correctly typed. The key changes include:
1. **Size Variants:** Added support for sm, md, and lg sizes, allowing more flexibility in the badge's appearance.
2. **ColorScheme Typing:** Utilized the ColorScheme type from @chakra-ui/react to ensure type safety and autocompletion for the colorScheme property.
3. **TypeScript Definitions**: Updated the BadgeProps interface to include the new size and variant properties while extending from ChakraBadgeProps.
These improvements enhance the flexibility and robustness of the Badge component, making it easier to use and maintain.
Changes
1. Updated Badge component to support **2xs,** **xs**(default one that we use right now …
=> chore(norhtlight): badge sizes improvement

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts
This commit resolves the issue where we wanted to add Next Week as an option in the date range picker. Previously, we had This Week and Last Week, but users can now also select Next Week. 
https://github.com/user-attachments/assets/4ee6ecce-1280-480a-87c5-3a4dd24ae654
closes: #DEV-13744
=> feat(northlight-ui): add next week to date range picker

framework/lib/components/toolbox/toolbox-content.tsx, framework/lib/components/toolbox/toolbox.tsx
Toolbox content accepts sx as prop in order to be able to override styling. Changed children wrapper in toolbox from box to vstack to be able to use flex grow for children
=> chore(framework): add sx to toolbox content

framework/lib/components/tooltip/tooltip.tsx, framework/lib/theme/components/tooltip/index.ts
This PR updates the default tooltip style by replacing the old "mediatoolBlue" style with the variant="ghost" style as the new default.
Additionally, the default value for `hasIcon` has been changed from `hasIcon={ true }` to` hasIcon={ false }`, streamlining tooltip usage across the application and reducing unnecessary complexity.
Light:
Dark:
closes: DEV-16120
=> chore(norhtlight): new default tooltip style

framework/lib/components/select/select-field.tsx
Sometimes from the outside the value could be
set to null in which case it should still hide
the clear button
=> fix(framework): hide select clear button if value null

framework/lib/components/combo-picker/combo-picker.tsx
Now when no value prop is provided and default option/input is assigned this will also trigger the component's onChange
Closes DEV-15917
=> Trigger onChange with default value and better behavior

framework/lib/components/tooltip/tooltip.tsx, framework/lib/components/types/tooltipIconMap/index.ts, framework/lib/theme/components/tooltip/index.ts
Couple of minor updates for the `tooltip`
1. Changed the `variant="info"` icon.
From:
To:
Updated/Swaped the `variant="danger"` and `variant="error"` icons to match the purpose of the tooltip and define more straight to the point visual language:
For the `variant="danger"`
From:
To:
Added new types/mapping for the tooltip - `tooltipIconMap`
closes: DEV-16089
=> fix(northlight): tooltip style updates

framework/lib/components/select/select.tsx, framework/lib/components/select/types.ts
Previousely if the components prop definition changed those changes would not rerender. This was due to
useMemo hook only rendering on mount, an optional key function can now be supplied to rerender the sub-compoennts properly
=> fix(framework): handle updates to components prop in select

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts
The fiscal month and day is 0-11, which is not the same format as the date range picker check.
DEV-17031
=> fix(framework): fix select this fiscal year in date range picker

framework/lib/components/toolbox/toolbox.tsx, framework/lib/theme/components/toolbox/index.ts
Two updates
1. `borderWidth` & `borderColor` are now updated with semantic tokens
2. Fixed visual bug
**From this:**
**To this:**
closes: DEV-17582
=> fix(northlight): toolbox style updates

framework/lib/components/toast/toast.tsx
Updated AI variant description styling as per Figma sketches.
Before:
After:
=> fix(northlight): toast ai desc style

framework/lib/components/steps/step-list.tsx, framework/lib/components/steps/step.tsx, framework/lib/components/steps/steps.tsx, framework/lib/components/steps/types.ts, framework/lib/theme/components/steps/step/index.ts
`Step` component styles update 1:1 with Figma requirements
**Enhancements:**
1. Introduced a new `indicator` type/prop, supporting both numbers and icons.
2. Added styling for the indicator to ensure consistent visuals.
**Bug Fixes:**
1. Resolved the issue where clicking a step on NL's website caused it to disappear.
**Refinements:**
1. Updated tokens and improved semantic consistency across styles.
**Video 1** ( `indicator` showoff ):
https://github.com/user-attachments/assets/913878c2-bfbe-4fc0-abfe-b9dfcad8bb37
**Video 2** ( light/dark mode ):
https://github.com/user-attachments/assets/e4237656-84e5-435a-8b4a-bf3fbef0ff19
closes: DEV-17204
=> fix(northlight): step style updates

framework/lib/components/date-picker/components/calendar/components/get-week-number-start-of-month.ts, framework/lib/components/date-picker/components/calendar/components/standalone-calendar-grid.tsx, framework/lib/components/date-picker/components/calendar/constants.ts
This commit resolves the issue where the weeks in the date picker were incorrect. The previous solution did not follow the ISO week numbering rules, resulting in inaccurate week numbers. We are now taking into account the actual calendar days instead of simply counting and dividing by 7. 
https://github.com/user-attachments/assets/ffeb469f-4498-4237-acdc-5ce02a2e6a19
closes: #DEV-17786
=> fix(northlight-ui): fix weeks in date picker

framework/lib/components/date-picker/components/calendar/range-calendar.tsx, framework/lib/components/date-picker/components/calendar/types.ts, framework/lib/components/date-picker/date-picker-field/date-range-picker-field.tsx, framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/lib/components/date-picker/types.ts
This allows us to execute functions whenever the Save button is pressed. Previously we did not support this, and only closed the modal whenever Save was pressed
=> Add prop to dateRangePicker and dateRangePickerField

docs/src/docs/app.tsx, framework/package.json
Org name change from Mediatool to Camphouse on the landing page, due to the latest rebranding
=> fix(northlight): org name change

framework/lib/components/flip-button/types.ts
This commit resolves the issue where the FlipButtonGroupField wouldnt show all the values. This was due to the props not being able to take string[] which can be the case when selecting datasets in reports for example. Ive added the possibility to pass string[] aswell to the value so we can now pass array with string. 
closes: #DEV-19393
=> fix(northlight-ui): update type in flipbuttongroupfield

framework/lib/components/keyframes/index.ts, framework/lib/theme/components/blinker/index.ts, framework/lib/theme/components/file-picker/index.ts
This commit imports keyframes from @emotion/react instead of @chakra-ui. This will allow exporting the keyframes directly from emotion.
=> fix(framework): change keyframes import to emotion

framework/lib/components/date-picker/types.ts
This commit ignores the prop firstDayOfWeek that react-aria implements in v3.X.X. When installing the latest minor version the props will clash with the one defined in northlight.
=> feat(framework): ignore firstDayOfWeek prop from react-aria

framework/lib/theme/components/date-picker/index.ts
preventing layout clipping while preserving the intended highlight effect.
Before:
After:
=> fix(northlight): daterange input focus ring

framework/lib/theme/components/input/index.ts, framework/lib/theme/components/number-input/index.ts
This commit fixes the issue where the boxShadow on focused `Input` and `NumberInput` components would overflow or get clipped by their parent wrappers.
The fix uses an `inset` boxShadow to keep the focus ring visually contained within the input boundaries, ensuring a cleaner and more consistent appearance across layouts.
**Before:**
**After:**
closes: DEV-8022
=> fix(northlight): input focus ring stays within boundaries

framework/lib/components/combo-picker/combo-picker.tsx
The nested input groups rendered unnecessary extra components that were overlapping the input field, which prevented getting focus on the input field when clicking on certain parts of the input. Removed excess so that the input gets focus in a more expected manner.
=> fix(framework): refactor combopicker

framework/lib/components/date-picker/date-picker/date-range-picker.tsx, framework/lib/components/date-picker/types.ts
Adds onCancelChanges prop to date range picker to allow for custom cancel behavior. This should have been in previous commit and release but was missed.
=> fix(framework): add onCancelChanges prop to date range picker
