mediatool/northlight

framework/sandbox/docs/app.tsx
framework/sandbox/index.html

chore(framework): Toned down start page for public domain

---

netlify.toml

fix: Add Netlify config file

---

framework/lib/components/checkbox/checkbox-field.tsx
framework/lib/components/checkbox/types.ts
framework/lib/components/switch/switch-field.tsx
framework/lib/components/switch/types.ts
framework/sandbox/docs/pages/field-page/index.tsx

This is a reopening of the PR: https://github.com/mediatool/mediatool/pull/11518 for the old @mediatool/ui that does not seem to have carried over to @northlight/ui during the migration

fix(framework): customize direction switch and checkbox

---

framework/lib/components/date-picker/date-picker/date-range-picker.tsx
framework/lib/components/date-picker/types.ts

Following the continuation of PR
https://github.com/mediatool/northlight/commit/f6424d3e86ccde6ec9996eca0177090fcdddceab (merged), there were some issues with typescript
when I tried to bump in media-overview/frontend
Try bumping yourselves in media-overview/frontend
to check if all isues were resolved.

fix(framework): fix date range picker types

---

framework/lib/components/date-picker/components/calendar/date-select/types.ts
framework/lib/components/file-picker/utils.ts
framework/lib/components/spinner/types.ts
framework/lib/components/steps/types.ts
framework/lib/components/tabs/types.ts
framework/lib/components/transitions/utils.ts
framework/lib/components/typography/headings/types.ts
framework/lib/theme/components/file-picker/index.ts
framework/sandbox/docs/app.tsx

This fix is resolving the giants block going out of the viewport issue, and causing the appearance of a horizontal scroll on the /components page after paolo's card was added.

fix(northlight/landing): Giants block causing page size issues

---

framework/lib/components/search-bar/types.ts
framework/lib/components/step-stack/step-stack.tsx
framework/sandbox/docs/pages/button-page/index.tsx
framework/tsconfig.json
framework/vite.config.ts

fix(framework): remove absolute imports

---

framework/lib/components/checkbox/checkbox-field.tsx
framework/lib/components/checkbox/types.ts

- Added 2 new props for better design handling
- Code updated for better responsiveness
- Documentation with example where you can play around
closes: DEV-8668

chore(northlight): new labelSize & labelPlacement props CheckboxField

---

framework/lib/components/select/select.tsx
framework/lib/hooks/use-select-callbacks/use-select-callbacks.ts

Fixed so that isNil is checking for val instead of value. Also added undefined val condition to second if block. Lastly, added an example of a clearable <Select> component to the docs.

fix(framework): value passed to onChange of use-select-callback

---

docs/CHANGELOG.md
docs/package.json
framework/CHANGELOG.md
framework/package.json

- @northlight/docs@1.1.14
- @northlight/ui@2.3.0

chore(northlight): publish 2.3.0

---

framework/lib/components/modal/modal.tsx
framework/lib/components/modal/types.ts

fix(framework): made modal unmount on close

---

framework/lib/components/text-field/text-field.tsx

fix(framework): do not allow blank space if isRequired true TextField

---

framework/lib/components/search-bar/get-components.tsx
framework/lib/components/select/types.ts
framework/lib/general.d.ts

fix(framework): add leftIcon prop to select

---

framework/lib/components/number-input/number-input.tsx
framework/lib/components/number-input/types.ts

fix(framework): made number input stepper arrows optional

---

framework/lib/theme/components/avatar/index.ts

fix(framework): shrink avatar font sizes

---

framework/lib/components/step-stack/step-stack.tsx

chore(northlight): removed redudant docs

---

framework/lib/components/select/get-matching-value.ts
framework/lib/components/select/index.ts
framework/lib/components/select/select.tsx
framework/lib/components/select/types.ts
framework/test/unit/components/select/get-matching-value-test.ts

DEV-9087
https://github.com/mediatool/northlight/assets/90923099/e9215d2a-bc7d-4a47-99e1-2872c9e977c2

fix(framework): allow string based values to select

---

framework/lib/components/toolbox/toolbox.tsx
framework/lib/components/toolbox/types.ts

https://github.com/mediatool/northlight/assets/81630176/ed70e97e-79a2-4e84-8867-8235c5a1c1d0
closes DEV-9359

feat(northlight): make toolbox dragable

---

framework/lib/components/index.ts
framework/lib/components/tags-input/index.ts
framework/lib/components/tags-input/tags-input-styles.ts
framework/lib/components/tags-input/tags-input.tsx
framework/lib/components/tags-input/types.ts

closed DEV-9250
https://github.com/mediatool/northlight/assets/90923099/31a926f4-2980-4653-a145-d8a673abfcfb

feat(framework): Tags Input

---

docs/src/tokens/components/visualizer/index.tsx
docs/src/tokens/pages/component-tokens-page/index.tsx
docs/src/tokens/pages/system-tokens-page/index.tsx
docs/src/tokens/routes/routes.tsx
docs/src/tokens/utils/component-tokens.ts
docs/src/tokens/utils/index.ts
docs/src/tokens/utils/system-tokens.ts
framework/lib/theme/skins/tott/index.ts
framework/lib/theme/skins/webapp/index.ts
tokens/index.ts
tokens/lib/tokens.json
tokens/package.json
tokens/scripts/sd-build.js

This PR properly enables system tokens and makes them independent from the component tokens
https://github.com/mediatool/northlight/assets/90923099/6d03df22-537c-43e3-8f24-b7c14a951c37

fix(tokens): remove system tokens from components tokens set

---

tokens/lib/tokens.json

From now on they will be available in code

chore(northlight): fixed core color tokens 

---

docs/src/tokens/app.tsx
framework/lib/components/carousel/carousel.tsx
framework/lib/components/drag-and-drop/draggable.tsx
framework/lib/components/file-picker/multi-file-uploader.tsx
framework/lib/components/tag/tag-group.tsx
framework/lib/components/tags-input/tags-input.tsx
framework/lib/components/transitions/collapse.tsx
framework/lib/components/transitions/fade.tsx
framework/lib/components/transitions/scale-fade.tsx
framework/lib/theme/components/drag-and-drop/index.ts
framework/lib/theme/components/table/index.ts

Replacing the token names with the names from the new structure.
closes: DEV-9505

fix(northlight): replace used tokens names

---

framework/lib/components/number-input/number-input-stepper.tsx

closed: DEV-9560
https://github.com/mediatool/northlight/assets/90923099/f208488a-0fb4-4a1f-a837-4a1fdcc62c92

fix(framework): bg color on hover for number-input stepper

---

framework/lib/components/switch/switch-field.tsx
framework/lib/components/switch/types.ts

- labelSize added
- Flex / Alignment fixes
closes: DEV-8557

chore(northlight): new labelSize prop for SwitchField

---

framework/lib/components/clipboard-input/clipboard-input.tsx

fix(framework): wrap clipboardinput in forward ref and text overflow

---

framework/lib/components/color-picker/color-picker.tsx
framework/lib/components/color-picker/types.ts

fix(framework): make color picker popover adjustable

---

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts

https://github.com/mediatool/northlight/assets/90923099/582bcd18-ab4b-4e65-ae6f-d73de7707157

fix(framework): add year to date option to date-range-picker

---

docs/src/reference/reference-page/index.tsx
docs/src/reference/reference-page/props-table.tsx

closed: DEV-9766
https://github.com/mediatool/northlight/assets/90923099/04db6391-a6f0-42c0-b79f-cbeac6239e37

fix(docs): fix broken link since moved northlight package

---

framework/lib/components/toolbox/toolbox.tsx
framework/lib/components/toolbox/types.ts

feat(framework): add bigger sizes to toolbox

---

framework/lib/components/button/button.tsx

fix(docs): add missing linkbox

---

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts

fix(framework): Range picker quick-select quarter off by one month

---

framework/lib/theme/skins/webapp/index.ts
tokens/lib/tokens.json

Deleted .over part from the link's token name

chore(northlight): Edited color typography tokens v2

---

docs/src/app/components/page.tsx
docs/src/app/components/search-components-bar/search-components-bar.tsx
docs/src/docs/pages/checkbox-page/index.tsx
docs/src/docs/pages/date-range-picker-page/index.tsx
docs/src/docs/pages/field-page/index.tsx
docs/src/docs/pages/file-picker-page/index.tsx
docs/src/docs/pages/form-demo-page/form-two.tsx
docs/src/docs/pages/form-demo-page/index.tsx
docs/src/docs/pages/form-page/index.tsx
docs/src/docs/pages/input-page/index.tsx
docs/src/docs/pages/notification-icon-button-page/index.tsx
docs/src/docs/pages/number-input-page/index.tsx
docs/src/docs/pages/progress-bar-page/index.tsx
docs/src/docs/pages/radio-button-page/index.tsx
docs/src/docs/pages/search-bar-page/index.tsx
docs/src/docs/pages/transitions-page/index.tsx
docs/src/icons/components/icons-grid/index.tsx
docs/src/reference/reference-page/index.tsx
docs/src/reference/reference-page/reference-page-wrapper.tsx
docs/src/routes.tsx
docs/src/tokens/components/tabs-page/index.tsx
docs/src/tokens/pages/about-tokens-page/index.tsx
docs/src/tokens/pages/tokens-picker-page/components/token-category.tsx
docs/src/tokens/pages/tokens-picker-page/utils/get-token-type.ts
docs/src/tokens/routes/routes.tsx
framework/lib/components/fast-grid/fast-grid.tsx
framework/lib/components/modal/types.ts

This should vastly improve the mobile usability for the rest of the documentation. It's not completely responsive but it should make the Northlight docs usable on mobile
https://github.com/mediatool/northlight/assets/90923099/3d50b87b-604b-4734-a808-dce9ea4f6bb4

docs(framework): add further mobile support

---

tokens/lib/tokens.json

Added new component tokens for table row

feat(tokens): Created color tokens for table row states

---

docs/src/app/components/search-components-bar/search-components-bar.tsx
docs/src/app/sandbox.tsx

https://github.com/mediatool/northlight/assets/90923099/81de220d-4f0e-4c85-8d6f-a0cd5e82cee7

fix(docs): add missing routes to search bar

---

framework/lib/components/toast/types.ts
framework/lib/components/toast/use-toast.tsx

closed: DEV-10207
https://github.com/mediatool/northlight/assets/90923099/47d7fc01-b98d-4f73-a0f9-a03c6d8ecd62

feat(framework): add replacePreviousToast prop

---

tokens/lib/tokens.json

Created tokens in webapp and tott for color sequence used in charts (initial tokens were pulled from master again)

feat(tokens): new tokens for chart color sequence

---

framework/lib/components/badge/badge.tsx
framework/lib/components/tooltip/index.ts
framework/lib/components/tooltip/tooltip.tsx
framework/lib/theme/components/tooltip/index.ts

https://github.com/mediatool/northlight/assets/90923099/310da87e-d5ca-42e3-8b69-71e79cc1d59f

feat(framework): tooltip varaints

---

docs/src/app/sandbox.tsx
docs/src/app/use-local-storage-state.ts

https://github.com/mediatool/northlight/assets/90923099/59c7b398-e53e-4808-a4d4-0898e95894d5

fix(docs): persist tottMode through localStorage

---

framework/lib/components/select/select.tsx

https://github.com/mediatool/northlight/assets/90923099/b166cb33-4ab8-4a1e-84f0-962edd53f32e

fix(framework): render select in portal by default

---

framework/lib/components/menu/index.ts
framework/lib/components/menu/menu.tsx
framework/lib/components/menu/types.ts
framework/lib/theme/components/menu/index.ts

- Added 2 new variants
- Style update and adaptation according to figma requirements
- Examples and documentation updated
closes: DEV-10542
**From this:**
**To this:**
https://github.com/mediatool/northlight/assets/5406237/fd5738f4-b12d-4f01-b727-35e3b67b9332
https://github.com/mediatool/northlight/assets/5406237/7767ee09-3ce6-4d65-a09f-3e6bdae1c216
And the sexy dark mode:

chore(northlight): component Menu style and variants update

---

framework/lib/theme/components/button/index.ts

-Button Revamp: Dialing up design unity with slick style updates.
-Token Refresh: New tokens in play for a snazzy rework.
-Theme Audit: Checked and matched for vibe consistency.
- `'outline'` variant Fix: Squashed the quirky hover/active bugs. Now it's all smooth sailing!
https://github.com/mediatool/northlight/assets/5406237/71581de9-44a1-4bf8-9656-2ebb504b16af

chore(northlight): button tokens & label updates

---

framework/lib/components/drag-and-drop/multi-sort.tsx

Previousely the useEffect which dependend on items caused an infinite render since it updated the items state indirectly which itself depended on

fix(framework): fix multi sort infinite re-render bug

---

framework/lib/components/alert/types.ts
framework/lib/components/tooltip/tooltip.tsx
framework/lib/components/types/toastIconMap/index.ts
framework/lib/theme/components/tooltip/index.ts
tokens/lib/tokens.json

Add examples of all avaliable tooltips.
Closes: DEV-10296

chore(framework/tokens): add tooltip to northlight

---

framework/lib/components/flip-button/flip-button.tsx

fix(framework): aria-label issue flip button

---

framework/lib/components/file-picker/file-picker.tsx
framework/lib/theme/components/file-picker/index.ts

fix(framework): make file picker full width by default

---

tokens/lib/tokens.json

Added semantic ai-alt color tokens to webapp and tott. They are going to be used as bg colors in ai-variant of toast/alert/tooltip

chore (northlight): added semantic ai-alt color token

---

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx
framework/lib/components/createable-select-dropdown/types.ts

there is now a currentOption prop that will set the currently selected option for the createable select component.

feat(lib): optional currentoption prop for createable select

---

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx
framework/lib/components/createable-select-dropdown/custom-components.tsx
framework/lib/components/createable-select-dropdown/types.ts

Some imports were referencing the package itself instead of the relative path

fix: imports that were wrong

---

README.md

added instructions on how to start the app

chore(northlight): update start app docs

---

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx
framework/lib/components/createable-select-dropdown/types.ts

there is now a menuPlacement prop that is used to control the placement of the select dropdown.
closes DEV-11339

feat(lib-createable-select-dropdown): added menuPlacement prop

---

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx
framework/package.json
yarn.lock

This commit corrects the dropdown width to use full space and removes duplications when creating a new option.
closes: DEV-12853

fix(framework): fix width and duplication issue in dropdown

---

framework/lib/components/createable-select-dropdown/createable-select-dropdown.tsx

Fixed issue with CreatableSelectDropdown menu appearing behind other elements; adjustments ensure it always appears on top now.

fix(framework): fix menu issue in dropdown

---

framework/lib/components/date-picker/components/calendar/components/range-cell.tsx
framework/lib/components/date-picker/components/calendar/date-select/month-select.tsx
framework/lib/components/date-picker/components/calendar/quick-navigation/quick-select.tsx
framework/lib/components/date-picker/date-picker/date-range-picker.tsx

fix(framework): date-range-picker-fixes

---

framework/lib/components/date-picker/components/calendar/calendar.tsx
framework/lib/components/date-picker/components/calendar/components/calendar-grid.tsx
framework/lib/components/date-picker/components/calendar/components/day-labels.tsx
framework/lib/components/date-picker/components/calendar/components/standalone-calendar-grid.tsx
framework/lib/components/date-picker/components/calendar/components/types.ts
framework/lib/components/date-picker/components/calendar/components/utils.ts
framework/lib/components/date-picker/components/calendar/range-calendar.tsx
framework/lib/components/date-picker/components/calendar/types.ts
framework/lib/components/date-picker/date-picker/date-picker.tsx
framework/lib/components/date-picker/date-picker/date-range-picker.tsx

This PR should:
-  set weekdays to english
- allow firstDayOfWeekProp
- Fix daylabels overflowing issues
For date and date range picker daylabels
Before:
After:
https://github.com/mediatool/northlight/assets/90923099/303a1a60-33db-4334-8560-a2ecc83a4132

Date picker and Date Range daylabels picker fixes

---

.github/CODEOWNERS

As discussed in the frontend team a designated
codeowner will be assigned for Northlight. The codeowner will look through every PR to see nothing breaks in app

chore(northlight): add CODEOWNERS file

---

framework/lib/components/file-picker/file-picker.tsx
framework/lib/theme/components/file-picker/index.ts

feature(framework): make file picker height customizable

---

framework/test/unit/components/color-picker/color-picker-test.tsx

fix(northlight-ui): fix color picker tests

---

framework/lib/components/avatar/avatar.tsx
framework/lib/theme/components/avatar/index.ts
framework/test/unit/utils/get-contrast-color/get-contrast-color-test.tsx

fix(framework): Update getContrastColor/contrast mismatch

---

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts

fix(framework): change option order in date picker quick navigation

---

framework/lib/components/combo-picker/combo-picker-field.tsx
framework/lib/components/combo-picker/combo-picker.tsx
framework/lib/components/combo-picker/types.ts

Replaced input for formattedInput
Closes: DEV-15705

feat(framework): use formattedInput in ComboPicker

---

framework/lib/components/combo-picker/combo-picker-field.tsx
framework/lib/components/combo-picker/combo-picker.tsx
framework/lib/components/combo-picker/types.ts

Changed the value's input property to be optional
Closes: DEV-16117

fix(framework): made input optional

---

framework/lib/components/combo-picker/combo-picker.tsx
framework/lib/components/combo-picker/types.ts
framework/lib/components/text-field/formatted-number-input.tsx
framework/lib/components/text-field/types.ts

With defaultToZeroIfEmpty we can make sure the ComboPicker always has an input value, for the cases in which we don't want input value to be optional
Closes: 86963qkcg

fix(framework): added defaultToZeroIfEmpty prop

---

framework/lib/components/combo-picker/combo-picker.tsx

Listen to defaultToZeroIfEmpty changes the set the input value to zero
Closes DEV-15917

fix(framework): listen to defaultToZeroIfEmpty changes

---

docs/src/docs/pages/form-demo-page/form-one.tsx
framework/lib/components/checkbox/checkbox-group-field.tsx
framework/lib/components/checkbox/checkbox.tsx
framework/lib/components/checkbox/index.ts
framework/lib/components/checkbox/types.ts

CheckboxGroupField

---

framework/lib/components/tags-input/tags-input.tsx

Makes tags-input work in toolbox.

fix(framework): make tags-input work in toolbox

---

framework/lib/components/flip-button/types.ts
framework/lib/theme/components/flip-button/index.ts

New variant added for white background on selection.

fix(framework): add white variant for flip button

---

framework/lib/components/combo-picker/combo-picker.tsx
framework/lib/components/text-field/types.ts

Extends type of comboPicker to accept chakra props

fix(framework): extends comboPicker to take chakra props

---

framework/lib/components/date-picker/components/calendar/quick-navigation/get-quick-select-options.ts
framework/lib/components/date-picker/components/calendar/quick-navigation/quick-select.tsx

fix(framework): add semester to quick select options in date picker

---

framework/lib/components/button/button.tsx

This is done due to people adding the spinner in an incorecct way

fix(framework): added docs for how to use is loading

---

framework/lib/components/badge/badge.tsx
framework/lib/components/badge/types.ts

This commit adds the possibility to add an icon and iconPosition to a badge.
**Result:**
https://github.com/user-attachments/assets/1fd041a7-47fe-4288-9da7-a83f662491ea

feat(northlight): badge icon

---

framework/lib/components/combo-picker/combo-picker.tsx

this commit adds a data-testid to the button inside of ComboPicker.

fix(framework): add test id to combo picker btn

---

framework/lib/components/combo-picker/combo-picker.tsx

Fix the placement of the opened menu for currency picker to be closer to the button opening the menu.

fix(framework): combopicker menu placement

---

framework/lib/theme/components/breadcrumb/index.ts

this old component just got updated with some new tokens so it can handle some theming in near future

fix(northlight): breadcrumbs tokens

---

framework/lib/components/date-picker/components/calendar/components/calendar-cell.tsx
framework/lib/components/date-picker/components/calendar/components/range-cell.tsx

This commit updates the reference calendar tokens with semantic tokens.

fix(norhtlight): datePicker tokens update

---

docs/src/icons/app.tsx

Icons documentation page reference tokens replaced with semantic tokens

fix(northlight): icons docs page

---

framework/lib/components/avatar/avatar-group.tsx
framework/lib/theme/components/avatar/index.ts

This fix replaces the reference tokens with semantic tokens

fix(northlight): avatar tokens update

---

docs/src/app/sandbox.tsx

new style theme switcher
https://github.com/user-attachments/assets/b8b53d9f-6635-4b5c-98c1-8de91d253850

feat(northlight): theme switcher

---

tokens/lib/tokens.json

This PR fixes standard radii for Camphouse theme: xs=2px, sm=4px, md=6px.

fix (tokens): fixes radii in camphouse theme

---

docs/src/app/components/main-menu.tsx
docs/src/app/components/nav-side-link.tsx

Updates the button style of the sidebar according to the theme selected.
https://github.com/user-attachments/assets/7a480f53-3866-412b-8801-d97ab98d9bc1

chore(northlight): sidebar btn style update
